name: "Terraform"

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Authenticate with Azure CLI using AZURE_CREDENTIALS
      - name: Azure Login
        run: |
          echo '${{ secrets.AZURE_CREDENTIALS }}' > azure_credentials.json
          az login --service-principal -u $(jq -r .clientId azure_credentials.json) -p $(jq -r .clientSecret azure_credentials.json) --tenant $(jq -r .tenantId azure_credentials.json)

      # Install Azure CLI
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      # Install the specific version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.ZIDAR }}
          terraform_version: 1.6.6 # Specify the version of Terraform you want to use

      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: terraform init

      # Generates an execution plan for Terraform
      - name: Terraform Plan
        run: |
          export PATH=$PATH:/opt/az/bin
          terraform plan -input=false
      # On push to "main", build or change infrastructure according to Terraform configuration files
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false

      # Deploy the .NET Core app to Azure Web App
      - name: Deploy .NET Core app to Azure Web App
        run: |
          az webapp deployment source config-zip -g Marathon1 -n marathon-api --src ./publish9.zip
      # Deploy the Client to Azure Web App
      - name: Deploy Frontend to Azure Web App
        run: |
          az webapp deployment source config-zip -g Marathon1 -n marathon-client --src ./build1.zip

